// General profile
export const SAVE_ROLES = 'SAVE_STAFF_ROLES';
export const SAVE_PERSONAL_INFO = 'SAVE_STAFF_BIO';
export const SAVE_LOCATION = 'SAVE_STAFF_BIO';

// export const CREATE_PROFILE_START = 'CREATE_PROFILE_START';
// export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
// export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL';

// export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
// export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
// export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

// export const DELETE_PROFILE_START = 'DELETE_PROFILE_START';
// export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';
// export const DELETE_PROFILE_FAIL = 'DELETE_PROFILE_FAIL';

// Staff profile
export const SAVE_STAFF_BIO = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_CERTIFICATE = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_EDUCATION = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_EXPERIENCE = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_MALPRAXIS = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_SERVICE = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_EXPERIENCE = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_EDUCATION = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_SERVICE = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_CERTIFICATE = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_MALPRAXIS = 'SAVE_STAFF_BIO';

// Patient profile
