// General profile
export const SAVE_ROLES = 'SAVE_STAFF_ROLES';
export const SAVE_PERSONAL_INFO = 'SAVE_STAFF_BIO';
export const SAVE_LOCATION = 'SAVE_STAFF_BIO';

// Staffs
export const SAVE_STAFF_BIO = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_CERTIFICATE = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_EDUCATION = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_EXPERIENCE = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_MALPRAXIS = 'SAVE_STAFF_BIO';
export const SAVE_STAFF_SERVICE = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_EXPERIENCE = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_EDUCATION = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_SERVICE = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_CERTIFICATE = 'SAVE_STAFF_BIO';
export const REMOVE_STAFF_MALPRAXIS = 'SAVE_STAFF_BIO';

// Patients
